
package com.est.webservice.server.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2015-11-17T15:02:15.462+08:00
 * Generated source version: 2.6.9
 * 
 */
 
public class IWeighTransService_WeighTransServiceImpPort_Server{

    protected IWeighTransService_WeighTransServiceImpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new IWeighTransServiceImpl();
        String address = "http://127.0.0.1:8080/weigh_jy/interface/weighjytrans";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new IWeighTransService_WeighTransServiceImpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
