package com.est.webservice.server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2015-11-17T15:02:15.456+08:00
 * Generated source version: 2.6.9
 * 
 */
@WebService(targetNamespace = "http://service.server.webservice.est.com/", name = "IWeighTransService")
@XmlSeeAlso({ObjectFactory.class})
public interface IWeighTransService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDownloads", targetNamespace = "http://service.server.webservice.est.com/", className = "com.est.webservice.server.service.GetDownloads")
    @WebMethod
    @ResponseWrapper(localName = "getDownloadsResponse", targetNamespace = "http://service.server.webservice.est.com/", className = "com.est.webservice.server.service.GetDownloadsResponse")
    public java.util.List<DownloadForClient> getDownloads(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            Long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "savUploadData", targetNamespace = "http://service.server.webservice.est.com/", className = "com.est.webservice.server.service.SavUploadData")
    @WebMethod
    @ResponseWrapper(localName = "savUploadDataResponse", targetNamespace = "http://service.server.webservice.est.com/", className = "com.est.webservice.server.service.SavUploadDataResponse")
    public String savUploadData(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            java.util.List<com.est.webservice.server.service.Weight> arg1
    );
}
