
package com.est.webservice.server.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2015-11-17T15:02:15.429+08:00
 * Generated source version: 2.6.9
 * 
 */
public final class IWeighTransService_WeighTransServiceImpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.server.webservice.est.com/", "IWeighTrans");

    private IWeighTransService_WeighTransServiceImpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = IWeighTrans.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IWeighTrans ss = new IWeighTrans(wsdlURL, SERVICE_NAME);
        IWeighTransService port = ss.getWeighTransServiceImpPort();  
        
        {
        System.out.println("Invoking getDownloads...");
        String _getDownloads_arg0 = "";
        Long _getDownloads_arg1 = null;
        java.util.List<DownloadForClient> _getDownloads__return = port.getDownloads(_getDownloads_arg0, _getDownloads_arg1);
        System.out.println("getDownloads.result=" + _getDownloads__return);


        }
        {
        System.out.println("Invoking savUploadData...");
        String _savUploadData_arg0 = "";
        java.util.List<com.est.webservice.server.service.Weight> _savUploadData_arg1 = null;
        String _savUploadData__return = port.savUploadData(_savUploadData_arg0, _savUploadData_arg1);
        System.out.println("savUploadData.result=" + _savUploadData__return);


        }

        System.exit(0);
    }

}
